name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: Vurv78/gmod-upload@v0.1.4
        with:
          id: 2256491552
          changelog: "Deployment via GitHub to commit ${GITHUB_SHA:0:7}"
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WORKSHOP_PASSWORD }}
